[build-system]
requires = ["setuptools>=60"]
build-backend = "setuptools.build_meta"

[project]
name = "muty"
version = "1.0.0"                                         # to be changed by CI
authors = [{ name = "Mentat", email = "info@mentat.is" }]
description = "our internal utilities :)"
readme = "README.md"
requires-python = ">=3.12"
