[build-system]
requires = ["setuptools>=68.0", "wheel", "setuptools_scm[toml]>=7.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/muty/_version.py"
version_scheme = "post-release"
local_scheme = "no-local-version"

[project]
name = "muty-python"
dynamic = ["version"]
authors = [{ name = "Mentat", email = "info@mentat.is" }]
description = "our internal utilities :)"
readme = "README.md"
requires-python = ">=3.12"

[tool.setuptools]
packages = ["muty"]
package-dir = {"" = "src"}